### ISSUE TITLE
difference of behavior between 2018-09/1.1.5 and 2019-12/1.5.0

### ISSUE THREAD

**Issue by mishka81** [alostale/luna-java-formatter#19]
Hi,

Since I migrated to a newer version of Eclipse (2019-12) and formatter v1.5.0 some of my old classes gets reformatted.

For example :

BEFORE :  
```
        buf.append(" style=\"font-size: " + size + "px;"
            + (StringUtils.isNotEmpty(style) ? " " + style : "") + "\"");
```

NOW :  

```
        buf.append(" style=\"font-size: " + size + "px;" + (StringUtils.isNotEmpty(style) ? " " + style
                        : "") + "\"");
```

Here is my formatter profile : [code-formatter.zip](https://github.com/alostale/luna-java-formatter/files/4972670/code-formatter.zip)

Is this a bug or am I missing something ? May be the formatter profile to update ?

Thanks for your help.

**Comment by MrKuip** [comment]
I'm having the same problem here!

BEFORE:

      return Duration.MILLISECOND.getUnitValue((double) mi_intake.getStopDate().getTime()
          - mi_intake.getStartDate().getTime());

AFTER:

      return Duration.MILLISECOND.getUnitValue((double) mi_intake.getStopDate().getTime() - mi_intake.getStartDate()
          .getTime());

**Comment by MrKuip** [comment]
It's is very annoying. Is this a known problem we cannot fix?

**Comment by isaki** [comment]
There is no easy fix for this; this is an artifact of Eclipse internals that this plugin relies on.
