### ISSUE TITLE
Weird line wrapping when using a comment inside a nested lambda/try-block (see example)

### ISSUE THREAD

**Issue by blablubbabc** [alostale/luna-java-formatter#3]
I am using oxygen1.a with the latest release here from github and stumbled across this issue with the 'old formatter'.

Example code, in initial (and desired) format:
```java
public int getPlayerCount() {
	synchronized (connector) {
		try {
			return connector.retry(() -> {
				connector.validateConnection();
				try (ResultSet resultSet = GET_PLAYER_COUNT.executeQuery()) {
					int playerCount = 0;
					if (resultSet.next()) {
						// a comment, messing things up somehow:
						playerCount = resultSet.getInt(1);
					}
					return playerCount;
				}
			});
		} catch (Exception e) {
			e.printStackTrace();
			return 0;
		}
	}
}
```

If I trigger the formatting it results in this:
```java
public int getPlayerCount() {
	synchronized (connector) {
		try {
			return connector.retry(() -> {
				connector.validateConnection();
				try (ResultSet resultSet = GET_PLAYER_COUNT.executeQuery()) {
					int playerCount = 0;
					if (resultSet.next()) {
						// a comment, messing things up somehow:
					playerCount = resultSet.getInt(1);
				}
				return playerCount;
			}
		})	;
		} catch (Exception e) {
			e.printStackTrace();
			return 0;
		}
	}
}
```
As you can see everything starting with the code line below the comment is shifted weirdly to the left.
If I remove the comment line, it formats correctly / as expected.

Here is the formatter profile I use for reference: https://pastebin.com/yuxBA21k

When switching to the eclipse default formatter (without changing any other formatter settings) it formats as expected, so my current assumption is that this is somehow related to the 'old formatter'. My hope is that someone here knows what's going on in case it's an issue with the 'Old formatter'.

If this is not caused by the 'Old formatter', then sorry for wasting your time..

**Comment by isaki** [comment]
This project is no longer supported by its owner; those of us keeping it from crashing in newer versions of eclipse are not familiar with the code base and are doing the bare minimum to keep this operational (i.e. this project is on life support, but barely). Feel free to submit a PR and I will review it. Closing ticket as it is very old.
