### ISSUE TITLE
Plugin doesn't work in Oxygen2 Release (4.7.2)

### ISSUE THREAD

**Issue by abgil** [alostale/luna-java-formatter#6]
I downloaded and compile the code, and also I installed the plugin in the plugins folder but eclipse doesn't recognize it.

**Comment by stephanroch** [comment]
It works for me with Oxygen 1a and 2 (4.7.2). But you have to drop the jar file into the folder named "**dropins**" in your Eclipse installation. Then eclipse will pick up this file and you can choose to have your code formated as in Luna.
